name: Display Tag and Environment

run-name: Display ${{ inputs.environment }} (${{ inputs.tag }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use (e.g., staging, production)'
        type: environment
        required: true
      tag:
        description: 'Tag to use (e.g., dev1, dev2)'
        type: choice
        options: [dev1, dev2, dev3, dev4, dev5, dev6, dev7, dev8, dev9, dev10, dev11, dev12]
        required: true
        default: dev1

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Display Inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Tag: ${{ inputs.tag }}"
